### ISSUE TITLE
ShadowRoot is not defined

### ISSUE THREAD

**Issue by codingcn** [antdv-pro/antdv-nuxt-starter#1]
新版本会报错`ShadowRoot is not defined`

package.json

```
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "npm run gen:css && nuxt build",
    "dev": "run-s gen:css  dev:nuxt",
    "dev:nuxt": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "gen:css": "esno scripts/genAntdStyle.ts"
  },
  "devDependencies": {
    "@ant-design-vue/nuxt": "^1.1.1",
    "@ant-design/icons-vue": "^6.1.0",
    "@nuxt/devtools": "latest",
    "@types/fs-extra": "^11.0.1",
    "@types/node": "^18.17.1",
    "ant-design-vue": "^4.0.3",
    "esno": "^0.17.0",
    "fs-extra": "^11.1.1",
    "npm-run-all": "^4.1.5",
    "nuxt": "^3.7.2",
    "sass": "^1.64.2",
    "@vueuse/nuxt": "^10.2.1"
  },
  "dependencies": {
    "dexie": "^3.2.4",
    "highlight.js": "^11.8.0",
    "marked": "^9.0.0",
    "marked-highlight": "^2.0.6",
    "protobufjs": "^7.2.5",
    "uuid": "^9.0.0"
  }
}

```

scripts/genAntdStyle.ts
```
import { extractStyle } from 'ant-design-vue/lib/_util/static-style-extract';
import fsExtra from 'fs-extra'
export const genAntdStyle = async () => {
  const css = extractStyle()
  await fsExtra.outputFile('public/css/antd.css', css, 'utf8')
}

genAntdStyle()

```

nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    app:{
        head: {
            link:[
                {
                    rel: 'stylesheet',
                    href:"/css/antd.css"
                }
            ]
        }
    },
    devtools:{enabled: false},
    modules: [
        '@ant-design-vue/nuxt'
    ],

    antd: {
        // Options
    },
    vite: {
        resolve: {
            alias: {
                'ant-design-vue/dist': 'ant-design-vue/dist',
                'ant-design-vue/es': 'ant-design-vue/es',
                'ant-design-vue/lib': 'ant-design-vue/es',
                'ant-design-vue': 'ant-design-vue/es',
            },
        },
    },
})

```

yarn dev
```
yarn run v1.22.19
$ run-s gen:css  dev:nuxt
$ esno scripts/genAntdStyle.ts
[Vue warn]: Invalid vnode type when creating vnode: undefined.
/Users/chris/Projects/my/dida/web/node_modules/ant-design-vue/node_modules/@ant-design/icons-vue/lib/utils.js:120
  return getRoot(ele) instanceof ShadowRoot;
                                 ^

ReferenceError: ShadowRoot is not defined
    at inShadow (/Users/chris/Projects/my/dida/web/node_modules/ant-design-vue/node_modules/@ant-design/icons-vue/lib/utils.js:120:34)
    at getShadowRoot (/Users/chris/Projects/my/dida/web/node_modules/ant-design-vue/node_modules/@ant-design/icons-vue/lib/utils.js:128:10)
    at <anonymous> (/Users/chris/Projects/my/dida/web/node_modules/ant-design-vue/node_modules/@ant-design/icons-vue/lib/utils.js:145:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "gen:css" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by Panyoujies** [comment]
同文 一样错误

**Comment by aibayanyu20** [comment]
https://github.com/ant-design/ant-design-icons/pull/600

先降级icons到6.1.0

**Comment by cuikaipeng** [comment]
> [ant-design/ant-design-icons#600](https://github.com/ant-design/ant-design-icons/pull/600)
> 
> 先降级icons到6.1.0

依旧还是不行

**Comment by Panyoujies** [comment]
> [ant-design/ant-design-icons#600](https://github.com/ant-design/ant-design-icons/pull/600)
> 
> 先降级图标到6.1.0

试过了 不行

**Comment by aibayanyu20** [comment]
https://stackblitz.com/edit/github-52q5xr-ve5njf?file=package.json

**Comment by Panyoujies** [comment]
> https://stackblitz.com/edit/github-52q5xr-ve5njf?file=package.json

我试试

**Comment by aibayanyu20** [comment]
升级@ant-design/icons-vue到7.0.1
